apiVersion: v1
kind: Service
metadata:
  name: kubepulse-service
spec:
  selector:
    app: kubepulse-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   # 🔥 IMPORTANT FIX
  type: NodePort